PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex: <http://example.org/game#>

# 0. Juegos mejor y peor evaluados (Cambiar DESC por ASC para ver los peores y Cambiar score por userScore para comparar criticos con usuarios)

SELECT ?name ?developerName ?platformName ?scoreValue
WHERE {
  ?game ex:score ?scoreValue ;
        rdfs:label ?name ;
        ex:developer ?developer ;
        ex:platform ?platform .
  ?developer rdfs:label ?developerName .
  ?platform rdfs:label ?platformName .
}
ORDER BY DESC(?scoreValue)
LIMIT 10

# 1. Diferencia entre opiniones de jugadores y criticos (ASC para ver juegos bien evaluados por criticos pero mal evaluados por jugadores y DESC para viseversa)

SELECT ?name ?developerName ?platformName ((xsd:decimal(?userScoreValue) * 10 - xsd:decimal(?scoreValue)) AS ?diff) ?scoreValue ?userScoreValue
WHERE {
  ?game ex:score ?scoreValue ;
        ex:userScore ?userScoreValue ;
        rdfs:label ?name ;
        ex:developer ?developer ;
        ex:platform ?platform .
  ?developer rdfs:label ?developerName .
  ?platform rdfs:label ?platformName .
}
ORDER BY ASC(?diff)
LIMIT 10

# 2. Promedio con pesos entre notas de criticos y usuarios.

SELECT ?name 
       ?developerName 
       ?platformName 
       ((FLOOR(((((xsd:decimal(?numUsers)/100)*xsd:decimal(?userScore)*10) + (xsd:decimal(?numCritics)*xsd:decimal(?criticScore)))/((xsd:decimal(?numUsers)/100)+(xsd:decimal(?numCritics)))))*100)/100 AS ?meanScore) 
       ?criticScore 
       ?userScore
WHERE {
  ?game ex:score ?criticScore ;
        ex:critics ?numCritics ;
        ex:userScore ?userScore ;
        ex:users ?numUsers ;
        rdfs:label ?name ;
        ex:developer ?developer ;
        ex:platform ?platform .
  ?developer rdfs:label ?developerName .
  ?platform rdfs:label ?platformName .
}
ORDER BY DESC(?meanScore)
LIMIT 10

# 3. Mejor developer y su mejor juego respectivo (probar con ex:score y ex:userScore)

SELECT ?developerName (FLOOR(AVG(?scoreValue)*100)/100 AS ?avgScore) (COUNT(?game) AS ?numGames) ?topGameName ?topScore
WHERE {
  ?game ex:developer ?developer ;
        ex:score ?scoreValue .
  ?developer rdfs:label ?developerName .
  
  {
    SELECT ?developer (SAMPLE(?gameName) AS ?topGameName) (MAX(?scoreValue) AS ?topScore)
    WHERE {
      ?g ex:developer ?developer ;
         ex:score ?scoreValue ;
         rdfs:label ?gameName .
    }
    GROUP BY ?developer
  }
}
GROUP BY ?developerName ?topGameName ?topScore
HAVING (COUNT(?game) >= 10)
ORDER BY DESC(?avgScore)
LIMIT 10

# 4. Mejor género y más popular por lustro con su mejor juego respectivo (ordenar por avgScore y numGames, y cambiar los rangos de lustro).

SELECT ?genreName (FLOOR(AVG(?scoreValue)*100)/100 AS ?avgScore) (COUNT(?game) AS ?numGames) ?topGameName ?topScore
WHERE {
  ?game ex:genre ?genre ;
        ex:score ?scoreValue ;
        ex:releaseDate ?releaseDate ;
        ex:critics ?critics .
  ?genre rdfs:label ?genreName .
  FILTER(?releaseDate >= "2016-01-01"^^xsd:date && ?releaseDate <= "2020-12-31"^^xsd:date && ?critics > 15)
  
  {
    SELECT ?genre (SAMPLE(?gameName) AS ?topGameName) (MAX(?scoreValue) AS ?topScore)
    WHERE {
      ?g ex:genre ?genre ;
         ex:score ?scoreValue ;
         ex:releaseDate ?releaseDate ;
         ex:critics ?critics ;
         rdfs:label ?gameName .
      FILTER(?releaseDate >= "2016-01-01"^^xsd:date && ?releaseDate <= "2020-12-31"^^xsd:date && ?critics > 15)
    }
    GROUP BY ?genre
  }
}
GROUP BY ?genreName ?topGameName ?topScore
HAVING (COUNT(?game) >= 10)
ORDER BY DESC(?avgScore)
LIMIT 3

# 5. Nota promedio del año y con mejor juego del año según criticos y usuarios

SELECT ?year (FLOOR(AVG(?scoreValue)*100)/100 AS ?criticAvg) (FLOOR(AVG(?userScoreValue)*100)/100 AS ?userAvg) ?topCriticGameName ?topCriticScore ?topUserGameName ?topUserScore
WHERE {
  ?game ex:score ?scoreValue ;
        ex:userScore ?userScoreValue ;
        ex:releaseDate ?date ;
        ex:users ?users ;
        ex:critics ?critics .
  FILTER(?users > 50)
  FILTER(?critics > 15)
  BIND(year(xsd:date(?date)) AS ?year)
  {
    SELECT ?yearTop1 
           (SAMPLE(?name1) AS ?topCriticGameName) 
           (MAX(?score1) AS ?topCriticScore)
    WHERE {
      ?g1 ex:score ?score1 ;
          ex:releaseDate ?d1 ;
          ex:users ?users1 ;
          ex:critics ?critics1 ;
          rdfs:label ?name1 .
      FILTER(?users1 > 50)
      FILTER(?critics1 > 15)
      BIND(year(xsd:date(?d1)) AS ?yearTop1)
    }
    GROUP BY ?yearTop1
  }
  {
    SELECT ?yearTop2 
           (SAMPLE(?name2) AS ?topUserGameName) 
           (MAX(?userScore2) AS ?topUserScore)
    WHERE {
      ?g2 ex:userScore ?userScore2 ;
          ex:releaseDate ?d2 ;
          ex:users ?users2 ;
          ex:critics ?critics2 ;
          rdfs:label ?name2 .
      FILTER(?users2 > 50)
      FILTER(?critics2 > 15)
      BIND(year(xsd:date(?d2)) AS ?yearTop2)
    }
    GROUP BY ?yearTop2
  }
  FILTER(?year = ?yearTop1)
  FILTER(?year = ?yearTop2)
}
GROUP BY ?year ?topCriticGameName ?topCriticScore ?topUserGameName ?topUserScore
ORDER BY ASC(?year)


# 6. Mejores plataformas por decada, con su mejor juego respectivo (probar con ex:score y ex:userScore, y cambiar los rangos de decadas).

SELECT ?platformName (FLOOR(AVG(?scoreValue)*100)/100 AS ?avgScore) (COUNT(?game) AS ?numGames) ?topGameName ?topScore
WHERE {
  ?game ex:platform ?platform ;
        ex:score ?scoreValue ;
        ex:releaseDate ?releaseDate ;
        ex:critics ?critics .
  ?platform rdfs:label ?platformName .
  
  FILTER(?releaseDate >= "1994-01-01"^^xsd:date && 
         ?releaseDate <= "2002-12-31"^^xsd:date)
  FILTER(?critics > 15)

  {
    SELECT ?platform (SAMPLE(?gameName) AS ?topGameName) (MAX(?scoreValue) AS ?topScore)
    WHERE {
      ?g ex:platform ?platform ;
         ex:score ?scoreValue ;
         ex:releaseDate ?releaseDate ;
         ex:critics ?critics ;
         rdfs:label ?gameName .
      
      FILTER(?releaseDate >= "1994-01-01"^^xsd:date && 
             ?releaseDate <= "2002-12-31"^^xsd:date)
      FILTER(?critics > 15)
    }
    GROUP BY ?platform
  }
}
GROUP BY ?platformName ?topGameName ?topScore
HAVING (COUNT(?game) >= 10)
ORDER BY DESC(?avgScore)
